name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build Node@${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ lts/*, current ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Before Install
        run: |
          git config --global user.name "flow-typed CI"
          git config --global user.email "noemail@example.com"
      - name: Tests
        run: ./build.sh
